name: Release
on:
  release:
    types:
      - created
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Configure Git User
        run: |
          git config --global user.name "hellotest"

      - run: lerna changed

      - run: npm ci --ignore-scripts --audit=false --fund=false

      - run: lerna run build --include-dependencies --since origin/master...HEAD

      - run: lerna version --conventional-commits --yes

      - run: lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
